# Generated by Django 2.0.5 on 2018-08-09 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20180809_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profle_pic',
            new_name='profile_pic',
        ),
    ]
